ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/urls.py
from django.urls import path
from map_A.views import designMapView, MarkersMapView, input_view, deserialize_map_json, create_marker, CombinedMapView

app_name = "map_A"

urlpatterns = [
    path("", input_view, name="input"),
    path("map/", designMapView.as_view(), name='map'),
    path("deserial/", deserialize_map_json, name='deserial'),
    path("create_note_pt/", create_marker, name='create_note_pt'),
    path('api/combined_map/', CombinedMapView.as_view(), name='combined_map')
]

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_site/urls.py
from django.contrib import admin
from django.urls import include, path
from map_A import views


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path('admindfsgdahfddfhnzdewehjncb/', admin.site.urls),
    path("api/", include("map_A.api")),
    path("map_A/", include("map_A.urls"), name="mappage"),
    #path("deserial/", views.deserialize_map_json, name = 'deserial'),
]

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/models.py
from django.contrib.gis.db import models


class Marker(models.Model):
    name = models.CharField(max_length=255)
    issue = models.CharField(max_length=255)
    location = models.PointField()

    def __str__(self):
        return self.name
    class Meta():
        managed = False
        db_table = "map_A_marker"
    
# joe migrate this so that we can see about making features from a geojson
class design(models.Model):
    #name = models.CharField(max_length=255)
    node_type = models.IntegerField()
    #geometry = models.PointField()
    created_user = models.CharField(max_length=255)
    globalid = models.CharField(max_length=50)
    #objectid = models.IntegerField()
    muuid = models.CharField(max_length=50)
    eversource_id = models.CharField(max_length=255)
    mav_site = models.CharField(max_length=255)
    node_config = models.IntegerField()
    label = models.CharField(max_length=255)
    inventory_status = models.IntegerField()
    gis_id = models.CharField(max_length=255)
    symbol_id = models.CharField(max_length=255)
    #created_date = models.DateField(null=True, blank=True)
    last_edited_user = models.CharField(max_length=255)
    last_edited_date = models.DateField(null=True, blank=True)
    wkb_geometry = models.PointField(srid=4326)
    comments = models.CharField(max_length=255)
    approved = models.BooleanField(default=None, null=True)
    ogc_fid = models.IntegerField(primary_key = True)

    def __str__(self):
        return self.ogc_fid

    class Meta():
         managed = False
         db_table = "map_A_test"

############################################################################################


class FiberCable(models.Model):
    ogc_fid = models.AutoField(primary_key=True)
    placement = models.CharField(max_length=100)
    cable_use = models.CharField(max_length=100)
    status = models.IntegerField()
    hierarchy = models.CharField(max_length=100)
    owner = models.CharField(max_length=100)
    workorderid = models.CharField(max_length=100, null=True, blank=True)
    globalid = models.UUIDField()
    cable_type = models.CharField(max_length=100)
    muuid = models.UUIDField()
    name = models.CharField(max_length=100, null=True, blank=True)
    shape_length = models.FloatField(null=True)
    wkb_geometry = models.LineStringField(null=False)

    def __str__(self):
        return self.name

    class Meta:
        managed = False
        db_table = "fibercable"

####################################################################################

class SpliceClosure(models.Model):
    ogc_fid = models.AutoField(primary_key=True)
    closure_make = models.CharField(max_length=100)
    closure_size = models.CharField(max_length=100)
    closure_use = models.CharField(max_length=100, null=True, blank=True)
    closure_splicecapacity = models.IntegerField(null=True, blank=True)
    hierachy = models.IntegerField()
    placement = models.CharField(max_length=100)
    status = models.IntegerField()
    owner = models.CharField(max_length=100)
    globalid = models.UUIDField()
    structureid = models.UUIDField()
    name = models.CharField(max_length=100, null=True, blank=True)
    wkb_geometry = models.PointField(null=False)

    def __str__(self):
        return self.name

    class Meta:
        managed = False
        db_table = "spliceclosure"

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/forms.py
#from django import forms
from .models import design, Marker
from django.contrib.gis import forms
#import floppyforms as forms

class designForm(forms.ModelForm):
    
    file = forms.FileField()

    class Meta():
        model = design
        exclude = ('approved','globalid', 'created_user', 'geometry', 'node_type')

class MarkerForm(forms.ModelForm):
    name = forms.CharField(required=True)
    location = forms.PointField(widget=
        forms.OSMWidget(attrs={'map_width': 800, 'map_height': 500, 'template_name': 'gis/openlayers-osm.html',
                               'default_lon': -71.18086608853581, 'default_lat': 42.368153586120975, 'default_zoom': 5}))

    class Meta:
        model = Marker
        exclude = ('',)

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/views.py
from django.shortcuts import render, redirect
from .models import design, Marker
from django.views.generic.base import TemplateView
from .forms import MarkerForm
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import json
from django.contrib.gis.geos import Point
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import FiberCableSerializer, SpliceClosureSerializer
from .models import FiberCable, SpliceClosure
#from django.contrib.auth.decorators import login_required

class designMapView(TemplateView):
    template_name = "map.html"

class MarkersMapView(TemplateView):
    template_name = "map.html"

def homepage(request):
    return render(request, "home.html")

def input_view(request):
    if request.method == "POST":
        form = MarkerForm(request.POST)
        if form.is_valid():
            marker = form.save(commit=False)
            marker.save()
            return redirect("homepage")

    form = MarkerForm()
    return render(request, "input.html", {"form": form})


###################################################################################################################################################################





# class CombinedMapView(APIView):
#     def get(self, request):
#         fibercables = FiberCable.objects.all() # limit to first 10 records
#         spliceclosures = SpliceClosure.objects.all()  # limit to first 10 records

#         fibercable_serializer = FiberCableSerializer(fibercables, many=True)
#         spliceclosure_serializer = SpliceClosureSerializer(spliceclosures, many=True)

#         return Response({
#             'fibercables': fibercable_serializer.data,
#             'spliceclosures': spliceclosure_serializer.data
#         })



class CombinedMapView(APIView):
    def get(self, request):
        fibercables = FiberCable.objects.all()[:3300]  # limit to first 10 records
        spliceclosures = SpliceClosure.objects.all()[:1000]  # limit to first 10 records

        fibercable_serializer = FiberCableSerializer(fibercables, many=True)
        spliceclosure_serializer = SpliceClosureSerializer(spliceclosures, many=True)

        return Response({
            'fibercables': fibercable_serializer.data,
            'spliceclosures': spliceclosure_serializer.data
        })



###############################################################################################################################################################################################################################################
#@login_required #for once login autheticate is set up
@csrf_exempt #IDT THIS IS A GREAT SOLUTION. SECURITY THING? WITHOUT THIS THOUGH {% csrf_token %} NEEDS TO BE CALLED IN HHTML WITHIN FORM TAG
#BUT WERE NOT USING A FORM TAG BECAUSE THE POST IS HAPPENING FROM JS.
def deserialize_map_json(request):
    if request.method == 'POST':
        try:
            #print(request.POST['created_user'])
            #^POST doesnt work it is always empty. i think because we arnt using a form. so decode body instead
            req_decode = request.body.decode("utf-8")
            
            #because we decoding request from byte it seems like its not fully in json format anymore. bool values like "true" instead of true
            #but it does make a dict which is useful
            req_decode_loads = json.loads(req_decode)
            print(req_decode_loads)

            #conditionals to fix non-json-y bool
            
            if req_decode_loads['approved'] == 'true':
                approved = True
            if req_decode_loads['approved'] == 'false':
                approved = False
            if req_decode_loads['approved'] == 'null':
                approved = None

            created_user = req_decode_loads['created_user']# if we needed to change this attribute, include in update method below

            #update  feature's approval  from popup. filter by primary key (fgc_id in database). django api refers to primary key as 'id'
            design.objects.filter(pk=req_decode_loads['id']).update(approved=approved)
            return HttpResponse("Status Updated!")
        
        except:
            return HttpResponse("something went wrong with post")
        
    else: 
        return render(request, "home.html")
    

@csrf_exempt
def create_marker(request):
    if request.method == 'POST':
        try:
            req_decode = request.body.decode("utf-8")
            req_decode_loads = json.loads(req_decode)
            print(req_decode_loads)

            #name = req_decode_loads['properties']['name']# if we needed to change this attribute, include in update method below
            issue = req_decode_loads['comment']# if we needed to change this attribute, include in update method below

            #create geometry
            latitude = float(req_decode_loads['latitude'])
            longitude = float(req_decode_loads['longitude'])
            pnt = Point(longitude, latitude)

            #both updating and creating will be made by this view
            if req_decode_loads['action'] == 'update':
                Marker.objects.filter(pk=req_decode_loads['id']).update(issue=issue, location=pnt)
                return HttpResponse("Status Updated!")
            if req_decode_loads['action'] == 'create':
                Marker.objects.create(issue=issue, location=pnt)
                return HttpResponse("Status Updated!")

        except:
            return HttpResponse("something went wrong with post")  
    else: 
        return render(request, "home.html")

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/templates/base.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<style>
	body { margin: 0; padding: 0; }
	#map { position: absolute; top: 0; bottom: 0; width: 100%; }

	.navbar {
  position: absolute;
  top: 0;
  width: 59%;
  z-index: 1;
  color: green;
  background-color: #f4eeee;
}
.navbar-brand, .navbar-nav > li > a {
  color: #1b6124;
  /* text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000; */

}

#map {
	position: absolute;
	top: 0;
	bottom: 0;
	width: 100%;
	z-index: 0; /* set a lower z-index for the map */
}

  /* .map-popup {
    padding: 15px;
    background-color: #c2b8b8;
    border-radius: 15px;
    font-size: 14px;
    line-height: 1.5;
  }

  .map-popup h4 {
    margin-top: 0;
    margin-bottom: 10px;
    font-size: 18px;
    font-weight: bold;
  }

  .map-popup p {
    margin-top: 0;
    margin-bottom: 10px;
  }

  .map-popup select {
  display: inline-block;
  margin-right: 5px;
  margin-bottom: 10px;
  width: 55%;
  padding: 6px 12px;
  font-size: 13px;
  line-height: 1.4;
  color: #555;
  vertical-align: middle;
  background-color: #fff;
  border: 1.5px solid #ccc;
  border-radius: 4px;
}

.map-popup button {
  display: inline-block;
  width: 40%;
  padding: 5px 5px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: 350;
  line-height: 1.4;
  text-align: center;
  border: 1px solid transparent;
  border-radius: 4px;
  color: #fff;
  background-color: #61b733;
  border-color: #626365;
} */

.maplibregl-popup_cool {
		margin: 0; 
		padding: 0;
		border-radius: 0px;
}


.maplibregl-popup.map-popup_cool {
    max-width: 240px;
    padding: 0;
}




.map-popup_cool {
    padding: 1em;
    color: #000;
    background-color: #858080; /* Set the background color to gray */
    border-radius: 5px; /* Add rounded corners to the pop-up */
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Add a subtle box shadow */
}
.map-popup_cool .mapboxgl-popup-close-button {
    position: absolute;
    top: 5px;
    right: 5px;
}

.map-popup_cool .card {
    width: 18rem;
}

.map-popup_cool .card-header {
    background-color: #3a6891;
    color: #fff;
    font-size: large;
    padding: 2px;
    font-weight: bold;
}

.map-popup_cool .card-body {
    font-size: 14px;
    line-height: 1.2;
}

.map-popup_cool .card-body p {
    margin-bottom: 0.5em;
}






</style>
</head>
<body>
  <nav class="navbar">
    <div class="container-fluid">
      <div class="navbar-header" style="display: flex;">
        <!-- Add a div element for the logo -->
        <div>
          <a class="navbar-brand" href="https://www.maverickcorporation.com/" style="display: flex; align-items: center;">
            <img src="{% static 'logo.jpg' %}" alt="Logo" width="100" height="150" class="img-responsive" style="margin-right: 10px;">
          </a>
        </div>
        <!-- Add a div element for the text -->
        <div>
          <a class="navbar-brand" style="display: flex; align-items: center;">
            <span style="font-size: 24px;">Maverick's Electric Vehicle Webmap Approval!</span>
          </a>
        </div>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'homepage' %}">Home</a></li>
          <li><a href="{% url 'map_A:input' %}">About</a></li>
          <li><a href="{% url 'map_A:map' %}">Approval Map</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% block content %}

{% endblock %}

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/templates/display_map.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Maverick Webmap Approval</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.js"></script>
<link href="https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.css" rel="stylesheet" />

</head>
<body>
  
	<div id="map"></div>
    
	<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
	<!-- <script src="map.js"></script> -->
  <script src="{% static 'map.js' %}" ></script>
{% endblock %}
</body>
</html>

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Maverick EV APPROVAL APP</title>
</head>
{% extends 'base.html' %}
{% block content %}

<body>
 <!-- <h1>Darmok and Jalad at Tanagra</h1> -->
 <br>
 <br>
 <h1>Shaka when the walls fell</h1>

</body>
{% endblock %}
</html>

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/templates/input.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {{ form.media }}
</head>

<body>
    <br>

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
                type="submit">submit
        </button>

        </form>

    </div>

    {% endblock %}
</body>
</html>

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/templates/map.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- <!DOCTYPE html> -->
<html>
<head>
<meta charset="utf-8" />
<title>Display a map</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
<script src="https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.js"></script>
<link href="https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.css" rel="stylesheet" />
<style>

	.maplibregl-popup-content {
		margin: 0; 
		padding: 0;
		border-radius: 15px;
	}
	/* body { margin: 10; padding: 0; }
	#map { position: absolute; top: 10%; bottom: 0; width: 100% ; } */
	#toggle-add-points-container {
    position: absolute;
    top: 120px;
    right: 20px;
    z-index: 1;
  }
  
  #toggle-add-points {
    background-color: #ffffff;
    border: 1px solid rgba(0, 0, 0, 0.15);
    padding: 6px 12px;
    font-size: 14px;
    cursor: pointer;
    border-radius: 3px;
  }

  #toggle-add-points:hover {
    background-color: #645a5a;
  }

  #toggle-add-points{
  display: inline-block;
  width: 100%;
  padding: 5px 5px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: 350;
  line-height: 1.4;
  text-align: center;
  border: 1px solid transparent;
  border-radius: 4px;
  color: #fff;
  background-color: #90ad80;
  border-color: #626365;
}



#bufferButton-container {
  position: absolute;
  top: 170px;
  right: 20px;
  z-index: 1;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}

#bufferDistance {
  width: 100px;
  margin-bottom: 5px;
}

#bufferButton {
  background-color: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.15);
  padding: 6px 12px;
  font-size: 14px;
  cursor: pointer;
  border-radius: 3px;
}

#bufferButton:hover {
  background-color: #645a5a;
}

#bufferButton {
  display: inline-block;
  padding: 5px 5px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: 350;
  line-height: 1.4;
  text-align: center;
  border: 1px solid transparent;
  border-radius: 4px;
  color: #fff;
  background-color: #90ad80;
  border-color: #626365;
}




#switch-basemap-container {
  position: absolute;
  top: 270px;
  right: 20px;
  z-index: 1;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}


#switch-basemap {
  background-color: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.15);
  padding: 6px 12px;
  font-size: 14px;
  cursor: pointer;
  border-radius: 3px;
}

#switch-basemap:hover {
  background-color: #645a5a;
}

#switch-basemap {
  display: inline-block;
  padding: 5px 5px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: 350;
  line-height: 1.4;
  text-align: center;
  border: 1px solid transparent;
  border-radius: 4px;
  color: #fff;
  background-color: #90ad80;
  border-color: #626365;
}

#filter-button-container {
  position: absolute;
  top: 320px;
  right: 20px;
  z-index: 1;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}


#filter-button {
  background-color: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.15);
  padding: 6px 12px;
  font-size: 14px;
  cursor: pointer;
  border-radius: 3px;
}

#filter-button:hover {
  background-color: #645a5a;
}

#filter-button {
  display: inline-block;
  padding: 5px 5px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: 350;
  line-height: 1.4;
  text-align: center;
  border: 1px solid transparent;
  border-radius: 4px;
  color: #fff;
  background-color: #90ad80;
  border-color: #626365;
}

#search-container {
    position: absolute;
    top: 10px;
    right: 50px; /* Adjust the value to move the search box left or right */
    z-index: 1;
  }

  #search-input {
    width: 200px;
    padding: 5px;
  }

  #search-button {
    padding: 5px 10px;
  }

  #fiber-cable-distribution {
  position: absolute;
  bottom: 550px;
  left: 20px;
  width: 150px;
  height: 150px;
  background-color: #dddddd;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

#fiber-cable-distribution h3 {
  font-size: 16px;
  margin-bottom: 5px;
  text-align: center;
}

#fiber-cable-distribution #pie-chart {
  width: 100%;
  height: 100%;
}

#fiber-cable-distribution p {
  margin: 0;
  text-align: center;
}

#fiber-cable-distribution p {
  margin: 0;
  text-align: center;
}

#fiber-cable-distribution p {
  margin: 0;
  font-size: 14px;
  text-align: center;
}

#fiber-cable-distribution #aerial-count {
  color: red;
}

#fiber-cable-distribution #underground-count {
  color: purple;
}

#zoom-widget {
  position: absolute;
  bottom: 10px;
  right: 10px;
  font-weight: bold;
}

#legend {
  position: absolute;
  left: -240px;
  bottom: -150px;
  display: flex;
  background-color: rgb(128, 117, 117);
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 10px
}

.legend-item {
  display: flex;
  align-items: center;
  margin-bottom: 5px;
  font-weight: bold
}

.legend-color {
  display: inline-block;
  width: 15px;
  height: 15px;
  border-radius: 100%; /* Make the shape a circle */
  border: 2px solid black; /* Add a black outline */
}

.legend-label {
  margin-left: 5px;
}

#legendContainer {
  position: absolute;
  top: 370px;
  right: 20px;
  z-index: 1;
}

#legendButton {
  display: inline-block;
  padding: 5px 5px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: 350;
  line-height: 1.4;
  text-align: center;
  border: 1px solid transparent;
  border-radius: 4px;
  color: #fff;
  background-color: #90ad80;
  border-color: #626365;
}

#legendButton:hover {
  background-color: #645a5a;
  color: #ffffff;
}

#legend {
  display: none;
  /* Additional styling properties for the legend */
  background-color: rgba(255, 255, 255, 0.8);
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 10px;
  color: #333;
}


.chart-container {
  width: 150px;
  height: 150px;
  background-color: #dddddd;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  margin-right: 20px;
}

.chart-container h3 {
  font-size: 16px;
  margin-bottom: 5px;
  text-align: center;
}

.chart-container canvas {
  width: 100%;
  height: 100%;
}

#Initial-Zoom-Level {
  position: absolute;
  bottom: 75px;
  left: 20px;
  width: 250px;
  height: 250px;
}

#initialZoomChart{
  width: 100%;
  height: 100%;
}

#spliceclosure-charts {
  width: 70px;
  height: 150px;
  background-color: #dddddd;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);

}

#Medium-Zoom-Level {
  position: absolute;
  bottom: 75px;
  left: 300px;
  width: 250px;
  height: 250px;
}

#MediumZoomChart{
  Width: 100%;
  height: 100%;
}

#Local-Zoom-Level {
  position: absolute;
  bottom: 75px;
  left: 575px;
  width: 250px;
  height: 250px;
}

#MediumZoomChart{
  Width: 100%;
  height: 100%;
}









</style>
	
<body>




  <div id="map">
    <!-- Add a container for the toggle button -->
    <div id="toggle-add-points-container">
      <button id="toggle-add-points">Enable Adding Points</button>
    </div>
    <div id="bufferButton-container">
      <button id="bufferButton">Show Buffer</button>
      <label for="bufferDistance">Buffer Distance (feet):</label>
      <input type="number" id="bufferDistance" value="20" min="0" step="1">
    </div>
    <div id="switch-basemap-container">
      <button id="switch-basemap">Switch Basemap</button>
    </div>
    <div id="filter-button-container">
      <button id="filter-button">Click for UG only</button>
    </div>
    <!-- Add the search input field and search button -->
    <div id="search-container">
      <input type="text" id="search-input" placeholder="Search by name">
      <button id="search-button">Search</button>
    </div>
  
    <!-- Add the legend button -->
    <div id="legendContainer">
      <button id="legendButton">Legend</button>
      <div id="legend"></div>
    </div>
  </div>

  <div id="spliceclosure-charts">
    <div id="Initial-Zoom-Level" class="chart-container">
      <h3><strong>LCP Cabinets </strong></h3>
      <canvas id="initialZoomChart"></canvas>
    </div>
  
    <div id="Medium-Zoom-Level" class="chart-container">
      <h3><strong>Splice Closures </strong></h3>
      <canvas id="mediumZoomChart"></canvas>
    </div>
  
    <div id="Local-Zoom-Level" class="chart-container">
      <h3><strong>Multi-Ports </strong></h3>
      <canvas id="localZoomChart"></canvas>
    </div>
  </div>
  

  <!-- Add the fiber cable distribution section -->
  <div id="fiber-cable-distribution">
    <h3><strong>Fiber Cable Distribution</strong></h3>
    <p id="aerial-count"></p>
    <p id="underground-count"></p>
    <canvas id="pie-chart"></canvas> 
  </div>

  <!-- Add the zoom widget -->
  <div id="zoom-widget" class="lower-right">
    Current Zoom Level: <span id="zoom-level"></span>
  </div>
  

  <!-- Include the required JavaScript files -->
  <script src="{% static 'basemap_no_imagery.js' %}"></script>
  <!-- <script src="{% static 'basemap_imagery.js' %}"></script> -->
  <!-- <script src="{% static 'status.js' %}"></script> -->
  <!-- <script src="{% static 'review.js' %}"></script> -->
  <script src="{% static 'spliceclosure.js' %}"></script>
  <script src="{% static 'spliceclosure_popup.js' %}"></script>
  <script src="{% static 'spliceclosure_legend.js' %}"></script> 
  <script src="{% static 'fibercable.js' %}"></script>
  <script src="{% static 'fibercable_filter_search.js' %}"></script>
  <script src="{% static 'fibercable_popup.js' %}"></script> 
  <!-- <script src="{% static 'bufffer.js' %}"></script> -->
  <script src="https://unpkg.com/@turf/turf@6/turf.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js/dist/Chart.min.js"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->


{% endblock %}
</body>
</html>

ShentelWebMap/ev-geodjango-jt_mapsite/map_site/map_A/templates/upload_design.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}


<body>

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
                type="submit" enctype="multipart/form-data">submit
        </button>
        </form>
    </div>


{% endblock %}
</body>
</html>